---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[code_deploy::default]
  - name: uninstall
    run_list:
      - recipe[code_deploy::install_agent]
      - recipe[code_deploy::uninstall_agent]
  - name: reinstall
    run_list:
      - recipe[code_deploy::install_agent]
      - recipe[code_deploy::uninstall_agent]
      - recipe[code_deploy::default]

verifier:
  name: inspec
