---
driver:
  name: docker
  privileged: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2
    driver_config:
      run_command: /usr/sbin/init

suites:
  - name: default
    run_list:
      - recipe[code_deploy::default]
  - name: disable
    run_list:
      - recipe[code_deploy::install_agent]
      - recipe[code_deploy::disable_agent]
      - recipe[code_deploy::stop_agent]
  - name: uninstall
    run_list:
      - recipe[code_deploy::install_agent]
      - recipe[code_deploy::uninstall_agent]
  - name: reinstall
    run_list:
      - recipe[code_deploy::install_agent]
      - recipe[code_deploy::uninstall_agent]
      - recipe[code_deploy::default]
verifier:
  name: inspec
